# Generated by Django 5.2.6 on 2025-10-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_job_accepted_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='Houston', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(default='Texas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='street_address',
            field=models.CharField(default='2500 Old Farm Rd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='zip_code',
            field=models.CharField(default='77477', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
