# Generated by Django 5.2.6 on 2025-10-24 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_proprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprofile',
            name='availability_notes',
            field=models.CharField(blank=True, help_text='e.g., Weekdays 9am-5pm, Emergency calls available', max_length=255),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link to Facebook profile (optional)'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='faq',
            field=models.TextField(blank=True, help_text="Optional FAQ section (e.g., Q: What's your hourly rate? A: ...)"),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link to Instagram profile (optional)'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='personal_website_url',
            field=models.URLField(blank=True, help_text='Link to personal website (optional)'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='services_offered',
            field=models.TextField(blank=True, help_text='Describe the main services you provide.'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Link to Twitter profile (optional)'),
        ),
        migrations.AddField(
            model_name='proprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'is_pro': False}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.job')),
                ('pro', models.ForeignKey(limit_choices_to={'is_pro': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'pro', 'customer')},
            },
        ),
    ]
