# Generated by Django 5.2.6 on 2025-10-24 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_proprofile_availability_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
