# Generated by Django 5.2.6 on 2025-10-24 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprofile',
            old_name='availability_notes',
            new_name='availability',
        ),
    ]
